### ISSUE TITLE
Portfolio Application Deployment 

### ISSUE THREAD

**Issue by Cabraham1** [Cabraham1/Cabraham1.github.io#1]
https://cabraham1.github.io/

**Comment by mckent05** [comment]
Hi @Cabraham1, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 

![approved](https://user-images.githubusercontent.com/73607512/207264069-11d9741f-6490-465b-8d4b-d5ced53e3251.gif)


## Highlights
- You have properly deployed your page on GitHub pages 👏 
- Good job updating your readme with a link to the live version of your portfolio 😄 
- Your PR is professional 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Cabraham1** [comment]
Thank you for approving my code
